# Generated by Django 3.2.25 on 2025-07-18 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewpost', '0002_rename_evaliation_reviewmodel_evaluation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmodel',
            name='images',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='reviewmodel',
            name='useful_review_record',
            field=models.TextField(blank=True, default=''),
        ),
    ]
